/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 13-ago-2021 0:26:43 				*/
/*  DBMS       : SQL Server 2000 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Almacen_Material_Almacen]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Almacen_Material] DROP CONSTRAINT [FK_Almacen_Material_Almacen]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Almacen_Material_Material]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Almacen_Material] DROP CONSTRAINT [FK_Almacen_Material_Material]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Almacen_Producto_Almacen]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Almacen_Producto] DROP CONSTRAINT [FK_Almacen_Producto_Almacen]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Almacen_Producto_Producto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Almacen_Producto] DROP CONSTRAINT [FK_Almacen_Producto_Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_MaterialComprado_Material]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [MaterialComprado] DROP CONSTRAINT [FK_MaterialComprado_Material]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_MaterialComprado_OrdenCompra]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [MaterialComprado] DROP CONSTRAINT [FK_MaterialComprado_OrdenCompra]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_MaterialPedido_Material]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [MaterialPedido] DROP CONSTRAINT [FK_MaterialPedido_Material]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_MaterialPedido_OrdenCompra]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [MaterialPedido] DROP CONSTRAINT [FK_MaterialPedido_OrdenCompra]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_OrdenCompra_Usuario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [OrdenCompra] DROP CONSTRAINT [FK_OrdenCompra_Usuario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_OrdenFabricacion_OrdenFabricacion]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [OrdenFabricacion] DROP CONSTRAINT [FK_OrdenFabricacion_OrdenFabricacion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_OrdenFabricacion_Pedido]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [OrdenFabricacion] DROP CONSTRAINT [FK_OrdenFabricacion_Pedido]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_OrdenFabricacion_Producto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [OrdenFabricacion] DROP CONSTRAINT [FK_OrdenFabricacion_Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Pedido_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Pedido] DROP CONSTRAINT [FK_Pedido_Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Pedido_Usuario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Pedido] DROP CONSTRAINT [FK_Pedido_Usuario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Pedido_Detalle_Pedido]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Pedido_Detalle] DROP CONSTRAINT [FK_Pedido_Detalle_Pedido]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Pedido_Detalle_Producto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Pedido_Detalle] DROP CONSTRAINT [FK_Pedido_Detalle_Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_PlantillaF_Material_Material]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [PlantillaF_Material] DROP CONSTRAINT [FK_PlantillaF_Material_Material]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_PlantillaF_Material_PlantillaFabricacion]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [PlantillaF_Material] DROP CONSTRAINT [FK_PlantillaF_Material_PlantillaFabricacion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_PlantillaF_SubProducto_PlantillaFabricacion]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [PlantillaF_SubProducto] DROP CONSTRAINT [FK_PlantillaF_SubProducto_PlantillaFabricacion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_PlantillaF_SubProducto_Producto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [PlantillaF_SubProducto] DROP CONSTRAINT [FK_PlantillaF_SubProducto_Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_PlantillaFabricacion_Producto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [PlantillaFabricacion] DROP CONSTRAINT [FK_PlantillaFabricacion_Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Producto_Material_Material]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Producto_Material] DROP CONSTRAINT [FK_Producto_Material_Material]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Producto_Material_Producto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Producto_Material] DROP CONSTRAINT [FK_Producto_Material_Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Producto_Producto_Producto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Producto_Producto] DROP CONSTRAINT [FK_Producto_Producto_Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Producto_Producto_SubProducto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Producto_Producto] DROP CONSTRAINT [FK_Producto_Producto_SubProducto]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Almacen]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Almacen]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Almacen_Material]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Almacen_Material]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Almacen_Producto]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Almacen_Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cliente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Material]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Material]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[MaterialComprado]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [MaterialComprado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[MaterialPedido]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [MaterialPedido]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[OrdenCompra]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [OrdenCompra]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[OrdenFabricacion]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [OrdenFabricacion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Pedido]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Pedido]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Pedido_Detalle]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Pedido_Detalle]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[PlantillaF_Material]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [PlantillaF_Material]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[PlantillaF_SubProducto]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [PlantillaF_SubProducto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[PlantillaFabricacion]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [PlantillaFabricacion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Producto]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Producto_Material]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Producto_Material]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Producto_Producto]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Producto_Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Usuario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Usuario]
GO

/* Create Tables */

CREATE TABLE [Almacen]
(
	[Id] uniqueidentifier NOT NULL,
	[Nombre] varchar(50) NULL
)
GO

CREATE TABLE [Almacen_Material]
(
	[IdAlmacen] uniqueidentifier NOT NULL,
	[IdMaterial] uniqueidentifier NOT NULL,
	[Cantidad] float NULL
)
GO

CREATE TABLE [Almacen_Producto]
(
	[IdAlmacen] uniqueidentifier NOT NULL,
	[IdProducto] uniqueidentifier NOT NULL,
	[Cantidad] float NULL
)
GO

CREATE TABLE [Cliente]
(
	[Id] uniqueidentifier NOT NULL,
	[Nombre] varbinary(50) NULL,
	[TipoDocumento] varchar(4) NULL,
	[NroDocumento] varchar(15) NULL,
	[Email] varchar(50) NULL,
	[Telefono] varchar(20) NULL
)
GO

CREATE TABLE [Material]
(
	[Id] uniqueidentifier NOT NULL,
	[Nombre] varchar(50) NOT NULL,
	[Unidad] varchar(3) NOT NULL,
)
GO

CREATE TABLE [MaterialComprado]
(
	[IdOrdenCompra] uniqueidentifier NOT NULL,
	[IdMaterial] uniqueidentifier NOT NULL,
	[Cantidad] float NULL,
)
GO

CREATE TABLE [MaterialPedido]
(
	[IdOrdenCompra] uniqueidentifier NOT NULL,
	[IdMaterial] uniqueidentifier NOT NULL,
	[Cantidad] float NULL,
)
GO

CREATE TABLE [OrdenCompra]
(
	[Id] uniqueidentifier NOT NULL,
	[IdSolicitante] uniqueidentifier NULL,
	[Estado] varchar(5) NULL,
	[FechaObjetivo] datetime NULL,
	[FechaEstimadaRecepcion] datetime NULL,
	[FechaRealRecepcion] datetime NULL
)
GO

CREATE TABLE [OrdenFabricacion]
(
	[Id] uniqueidentifier NOT NULL,
	[IdOrdenFabricacionPosterior] uniqueidentifier NULL,
	[Estado] varbinary(5) NOT NULL,
	[IdPedido] uniqueidentifier NOT NULL,
	[IdProducto] uniqueidentifier NOT NULL,
	[CantObjetivo] int NOT NULL,
	[CantFabricados] int NULL,
	[CantAprobados] int NULL
)
GO

CREATE TABLE [Pedido]
(
	[Id] uniqueidentifier NOT NULL,
	[Estado] varchar(50) NOT NULL,
	[IdSolicitante] uniqueidentifier NULL,
	[IdVendedor] uniqueidentifier NOT NULL
)
GO

CREATE TABLE [Pedido_Detalle]
(
	[IdPedido] uniqueidentifier NOT NULL,
	[IdProducto] uniqueidentifier NOT NULL,
	[Cantidad] int NULL
)
GO

CREATE TABLE [PlantillaF_Material]
(
	[IdPlantilla] uniqueidentifier NOT NULL,
	[IdMaterial] uniqueidentifier NOT NULL,
	[Cantidad] float NULL
)
GO

CREATE TABLE [PlantillaF_SubProducto]
(
	[IdPlantilla] uniqueidentifier NOT NULL,
	[IdSubProducto] uniqueidentifier NOT NULL,
	[Cantidad] float NULL
)
GO

CREATE TABLE [PlantillaFabricacion]
(
	[IdProducto] uniqueidentifier NOT NULL,
	[ReposoMinRequeridoHs] int NULL
)
GO

CREATE TABLE [Producto]
(
	[Id] uniqueidentifier NOT NULL,
	[Nombre] varchar(50) NOT NULL,
	[Unidad] varchar(3) NOT NULL,
	[Descripcion] varchar(50) NULL,
	[Foto] varchar(100) NULL
)
GO

CREATE TABLE [Producto_Material]
(
	[IdMaterial] uniqueidentifier NOT NULL,
	[IdProducto] uniqueidentifier NOT NULL
)
GO

CREATE TABLE [Producto_Producto]
(
	[IdProducto] uniqueidentifier NOT NULL,
	[IdSubProducto] uniqueidentifier NOT NULL
)
GO

CREATE TABLE [Usuario]
(
	[Id] uniqueidentifier NOT NULL,
	[Usuario] varchar(30) NULL,
	[Clave] varchar(50) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Almacen] 
 ADD CONSTRAINT [PK_Almacen]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Almacen_Material] 
 ADD CONSTRAINT [PK_Almacen_Material]
	PRIMARY KEY CLUSTERED ([IdAlmacen] ASC,[IdMaterial] ASC)
GO

ALTER TABLE [Almacen_Producto] 
 ADD CONSTRAINT [PK_Almacen_Producto]
	PRIMARY KEY CLUSTERED ([IdAlmacen] ASC,[IdProducto] ASC)
GO

ALTER TABLE [Cliente] 
 ADD CONSTRAINT [PK_Cliente]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Material] 
 ADD CONSTRAINT [PK_Material]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [MaterialComprado] 
 ADD CONSTRAINT [PK_MaterialComprado]
	PRIMARY KEY CLUSTERED ([IdOrdenCompra] ASC,[IdMaterial] ASC)
GO

ALTER TABLE [MaterialPedido] 
 ADD CONSTRAINT [PK_MaterialPedido]
	PRIMARY KEY CLUSTERED ([IdOrdenCompra] ASC,[IdMaterial] ASC)
GO

ALTER TABLE [OrdenCompra] 
 ADD CONSTRAINT [PK_OrdenCompra]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [OrdenFabricacion] 
 ADD CONSTRAINT [PK_OrdenFabricacion]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Pedido] 
 ADD CONSTRAINT [PK_Pedido]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Pedido_Detalle] 
 ADD CONSTRAINT [PK_Pedido_Detalle]
	PRIMARY KEY CLUSTERED ([IdPedido] ASC,[IdProducto] ASC)
GO

ALTER TABLE [PlantillaF_Material] 
 ADD CONSTRAINT [PK_PlantillaF_Material]
	PRIMARY KEY CLUSTERED ([IdPlantilla] ASC,[IdMaterial] ASC)
GO

ALTER TABLE [PlantillaF_SubProducto] 
 ADD CONSTRAINT [PK_PlantillaF_SubProducto]
	PRIMARY KEY CLUSTERED ([IdPlantilla] ASC,[IdSubProducto] ASC)
GO

ALTER TABLE [PlantillaFabricacion] 
 ADD CONSTRAINT [PK_PlantillaFabricacion]
	PRIMARY KEY CLUSTERED ([IdProducto] ASC)
GO

ALTER TABLE [Producto] 
 ADD CONSTRAINT [PK_Producto]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Producto_Material] 
 ADD CONSTRAINT [PK_Producto_Material]
	PRIMARY KEY CLUSTERED ([IdMaterial] ASC,[IdProducto] ASC)
GO

ALTER TABLE [Producto_Producto] 
 ADD CONSTRAINT [PK_Producto_Producto]
	PRIMARY KEY CLUSTERED ([IdProducto] ASC,[IdSubProducto] ASC)
GO

ALTER TABLE [Usuario] 
 ADD CONSTRAINT [PK_Usuario]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Usuario] 
 ADD CONSTRAINT [UQ_Usuario] UNIQUE NONCLUSTERED ([Usuario] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Almacen_Material] ADD CONSTRAINT [FK_Almacen_Material_Almacen]
	FOREIGN KEY ([IdAlmacen]) REFERENCES [Almacen] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Almacen_Material] ADD CONSTRAINT [FK_Almacen_Material_Material]
	FOREIGN KEY ([IdMaterial]) REFERENCES [Material] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Almacen_Producto] ADD CONSTRAINT [FK_Almacen_Producto_Almacen]
	FOREIGN KEY ([IdAlmacen]) REFERENCES [Almacen] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Almacen_Producto] ADD CONSTRAINT [FK_Almacen_Producto_Producto]
	FOREIGN KEY ([IdProducto]) REFERENCES [Producto] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [MaterialComprado] ADD CONSTRAINT [FK_MaterialComprado_Material]
	FOREIGN KEY ([IdMaterial]) REFERENCES [Material] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [MaterialComprado] ADD CONSTRAINT [FK_MaterialComprado_OrdenCompra]
	FOREIGN KEY ([IdOrdenCompra]) REFERENCES [OrdenCompra] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [MaterialPedido] ADD CONSTRAINT [FK_MaterialPedido_Material]
	FOREIGN KEY ([IdMaterial]) REFERENCES [Material] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [MaterialPedido] ADD CONSTRAINT [FK_MaterialPedido_OrdenCompra]
	FOREIGN KEY ([IdOrdenCompra]) REFERENCES [OrdenCompra] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [OrdenCompra] ADD CONSTRAINT [FK_OrdenCompra_Usuario]
	FOREIGN KEY ([IdSolicitante]) REFERENCES [Usuario] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [OrdenFabricacion] ADD CONSTRAINT [FK_OrdenFabricacion_OrdenFabricacion]
	FOREIGN KEY ([IdOrdenFabricacionPosterior]) REFERENCES [OrdenFabricacion] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [OrdenFabricacion] ADD CONSTRAINT [FK_OrdenFabricacion_Pedido]
	FOREIGN KEY ([IdPedido]) REFERENCES [Pedido] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [OrdenFabricacion] ADD CONSTRAINT [FK_OrdenFabricacion_Producto]
	FOREIGN KEY ([IdProducto]) REFERENCES [Producto] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Pedido] ADD CONSTRAINT [FK_Pedido_Cliente]
	FOREIGN KEY ([IdSolicitante]) REFERENCES [Cliente] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Pedido] ADD CONSTRAINT [FK_Pedido_Usuario]
	FOREIGN KEY ([IdVendedor]) REFERENCES [Usuario] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Pedido_Detalle] ADD CONSTRAINT [FK_Pedido_Detalle_Pedido]
	FOREIGN KEY ([IdPedido]) REFERENCES [Pedido] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Pedido_Detalle] ADD CONSTRAINT [FK_Pedido_Detalle_Producto]
	FOREIGN KEY ([IdProducto]) REFERENCES [Producto] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [PlantillaF_Material] ADD CONSTRAINT [FK_PlantillaF_Material_Material]
	FOREIGN KEY ([IdMaterial]) REFERENCES [Material] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [PlantillaF_Material] ADD CONSTRAINT [FK_PlantillaF_Material_PlantillaFabricacion]
	FOREIGN KEY ([IdPlantilla]) REFERENCES [PlantillaFabricacion] ([IdProducto]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [PlantillaF_SubProducto] ADD CONSTRAINT [FK_PlantillaF_SubProducto_PlantillaFabricacion]
	FOREIGN KEY ([IdPlantilla]) REFERENCES [PlantillaFabricacion] ([IdProducto]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [PlantillaF_SubProducto] ADD CONSTRAINT [FK_PlantillaF_SubProducto_Producto]
	FOREIGN KEY ([IdSubProducto]) REFERENCES [Producto] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [PlantillaFabricacion] ADD CONSTRAINT [FK_PlantillaFabricacion_Producto]
	FOREIGN KEY ([IdProducto]) REFERENCES [Producto] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Producto_Material] ADD CONSTRAINT [FK_Producto_Material_Material]
	FOREIGN KEY ([IdMaterial]) REFERENCES [Material] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Producto_Material] ADD CONSTRAINT [FK_Producto_Material_Producto]
	FOREIGN KEY ([IdProducto]) REFERENCES [Producto] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Producto_Producto] ADD CONSTRAINT [FK_Producto_Producto_Producto]
	FOREIGN KEY ([IdProducto]) REFERENCES [Producto] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Producto_Producto] ADD CONSTRAINT [FK_Producto_Producto_SubProducto]
	FOREIGN KEY ([IdSubProducto]) REFERENCES [Producto] ([Id]) ON DELETE No Action ON UPDATE No Action
GO
